### ISSUE TITLE
Pick a new IRC server.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/ByzPi#5]
ngircd isn't available in the Wheezy repositories.  We need to pick a new IRC server daemon, configure it for qwebirc, and get the config file we write into Git and the Puppet script.

We might have to package and install qwebirc, too.

**Comment by ElephantNinja** [comment]
Exhibit A - useful tables of IRC daemons like ngircd, for a potential hunt
for alternatives:
http://en.wikipedia.org/wiki/Comparison_of_Internet_Relay_Chat_daemons

Exhibit B - http://packages.debian.org/search?keywords=ngircd
wheezy (testing) http://packages.debian.org/wheezy/ngircd (net):
lightweight Internet Relay Chat server
19.2-2: amd64 armel armhf i386 ia64 kfreebsd-amd64 kfreebsd-i386 mips
mipsel powerpc s390 s390x sparc

**Comment by virtadpt** [comment]
Haxwithaxe has started working on a repo of config files for inspircd: https://github.com/Byzantium/inspircd-config/tree/master/etc/inspircd

**Comment by virtadpt** [comment]
Prior to the Mini-Maker Faire in Silver Spring I added Charybdis ircd (http://www.atheme.org/project/charybdis) and it works perfectly well.  Reference commit 1ef1caf630cc2bd6ee1f30a41a7415d4b3ed8672.
