### ISSUE TITLE
Package qwebirc.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/ByzPi#8]
Debian Wheezy doesn't seem to have a QwebIRC package.  I think we'll have to make our own .deb for it, and add the custom config file to Puppet.

**Comment by virtadpt** [comment]
http://qwebirc.org/installation#debian

**Comment by virtadpt** [comment]
How to package Python apps for Debian: https://wiki.debian.org/Python/Packaging

**Comment by ElephantNinja** [comment]
FYI http://en.wikipedia.org/wiki/Comparison_of_Internet_Relay_Chat_clients

**Comment by virtadpt** [comment]
Compilation process (documentation for later):
`cp config.py.example config.py`
`./compile.py`

More useful page: http://savetheions.com/2010/01/20/packaging-python-applicationsmodules-for-debian/

**Comment by virtadpt** [comment]
To do:
- Write, test, and package initscript.  Add to list of services started at boot-time.
- Add pseudouser that run.py will execute as.
- Ensure that config.py is added to Puppet manifest.
- Ensure that Apache configuration file to proxy QwebIRC is added to Puppet manifest.
- Add qwebirc.service mDNS descriptor file to package.
